---
- :name: Controller (Nova Network)
  :class:
  - quickstack::nova_network::controller
  - quickstack::ntp
- :name: Compute (Nova Network)
  :class:
  - quickstack::nova_network::compute
  - quickstack::ntp
- :name: Controller (Neutron)
  :class:
  - quickstack::neutron::controller
  - quickstack::ntp
- :name: Compute (Neutron)
  :class:
  - quickstack::neutron::compute
  - quickstack::ntp
- :name: Neutron Networker
  :class:
  - quickstack::neutron::networker
  - quickstack::ntp
- :name: Cinder Block Storage
  :class:
  - quickstack::storage_backend::cinder
  - quickstack::ntp
- :name: Load Balancer
  :class:
  - quickstack::load_balancer
  - quickstack::ntp
- :name: Swift Storage Node
  :class:
  - quickstack::swift::storage
  - quickstack::ntp
- :name: HA All In One Controller
  :class:
  - quickstack::openstack_common
  - quickstack::pacemaker::common
  - quickstack::pacemaker::params
  - quickstack::pacemaker::keystone
  - quickstack::pacemaker::swift
  - quickstack::pacemaker::load_balancer
  - quickstack::pacemaker::memcached
  - quickstack::pacemaker::qpid
  - quickstack::pacemaker::rabbitmq
  - quickstack::pacemaker::glance
  - quickstack::pacemaker::nova
  - quickstack::pacemaker::heat
  - quickstack::pacemaker::cinder
  - quickstack::pacemaker::horizon
  - quickstack::pacemaker::galera
  - quickstack::pacemaker::neutron
  - quickstack::pacemaker::nosql
  - quickstack::pacemaker::ceilometer
  - quickstack::ntp
- :name: Gluster Server
  :class:
  - puppet::vardir
  - quickstack::gluster::server
  - quickstack::ntp
- :name: Galera Server
  :class:
  - quickstack::galera::server
  - quickstack::ntp
